const aside = document.querySelector('#aside');
aside.innerHTML = `<ul>
<li id="index"><span>首頁</span></li>
<li>
    <span>資訊管理</span>
    <ul>
        <li>影城資訊管理</li>
        <li>電影資訊管理</li>
        <li>票價資訊管理</li>
        <li>餐飲資訊管理</li>
        <li>影廳資訊管理</li>
        <li>場次管理</li>
        <li>座位管理</li>
    </ul>
</li>
<li>
    <span>票務管理</span>
    <ul>
        <li>現場購票/購餐</li>
        <li>票務訂單管理</li>
        <li>驗票驗證碼</li>
    </ul>
</li>
<li>
    <span>評論相關</span>
    <ul>
        <li>舉報回應管理</li>
    </ul>
</li>
<li>
    <span>商城相關</span>
    <ul>
        <li>商品資訊</li>
        <li>商城訂單</li>
    </ul>
</li>
<li>
    <span>活動相關</span>
    <ul>
        <li>促銷活動管理</li>
        <li>許願池管理</li>
    </ul>
</li>
<li>
    <span>公告客服</span>
    <ul>
        <li>公告管理</li>
        <li>Q&A文字管理</li>
        <li>線上客服</li>
    </ul>
</li>
<li>
    <span>員工管理</span>
    <ul>
        <li>帳號與權限</li>
        <li>個人資料維護</li>
    </ul>
</li>
<li>
    <span>會員管理</span>
    <ul>
        <li>會員帳號管理</li>
    </ul>
</li>
</ul>`;